Repository drashland/rhum, pull requests merged in 2020-11, with the labels that each got.

#88 chore: Add youtube tutorials badge to readme
  README.md
Labels: Status: Approved, Type: Chore

#89 chore: Improve workflows
  .github/workflows/pre_release.yml
  .github/workflows/release.yml
  .gitignore
  console/bumper_ci_service.ts
  console/bumper_ci_service_files.ts
  console/update_deno_version_strings.ts
Labels: Type: Chore

#91 fix: beforeAll() executing before each test case
  .gitignore
  src/test_case.ts
  tests/integration/hooks/before_all_test.ts
  tests/integration/hooks/before_each_test.ts
Labels: Type: Patch

#97 chore: Remove bloat
  .github/workflows/master.yml
  README.md
  console/bumper_ci_service_files.ts
Labels: Type: Chore
