Repository drashland/rhum, pull requests merged in 2022-04, with the labels that each got.

#150 feat!: move closer to test double definitions
  README.md
  mod.ts
  src/fake/fake_builder.ts
  src/fake/fake_mixin.ts
  src/interfaces.ts
  src/mock/mock_builder.ts
  src/mock/mock_mixin.ts
  src/mock_builder.ts
  src/pre_programmed_method.ts
  src/types.ts
  tests/deps.ts
  tests/integration/mock_test.ts
  tests/integration/stub_test.ts
  tests/unit/mock_builder_test.ts
  tests/unit/mod/dummy_test.ts
  tests/unit/mod/fake_test.ts
  tests/unit/mod/mock_test.ts
  tests/unit/mod/stub_test.ts
Labels: Type: Minor

#148 fix: Mocking a class with getters doesn't set default initialised value
  src/mock_builder.ts
  tests/deps.ts
  tests/integration/mock_test.ts
Labels: Type: Patch

#157 feat(v2): support node
  .gitignore
  babel.config.js
  console/build_esm_lib
  console/build_esm_lib.ts
  jest.config.ts
  package.json
  src/fake/fake_builder.ts
  src/mock/mock_builder.ts
  tests/cjs/unit/mod/dummy.test.js
  tests/cjs/unit/mod/fake.test.js
  tests/cjs/unit/mod/mock.test.js
  tests/cjs/unit/mod/stub.test.js
  tests/deno/deps.ts
  tests/deno/unit/mod/dummy_test.ts
  tests/deno/unit/mod/fake_test.ts
  tests/deno/unit/mod/mock_test.ts
  tests/deno/unit/mod/stub_test.ts
  tests/esm/jest_assertions.ts
  tests/esm/unit/mod/dummy.test.ts
  tests/esm/unit/mod/fake.test.ts
  tests/esm/unit/mod/mock.test.ts
  tests/esm/unit/mod/stub.test.ts
  tsconfig.cjs.json
  tsconfig.esm.json
  tsconfig.json
Labels: Type: Minor

#159 ci: add yarn publish
  .github/workflows/release.yml
Labels: Type: Chore

#132 BREAKING(v2): remove test runner; introduce test doubles
  .github/workflows/master.yml
  .github/workflows/release.yml
  .gitignore
  README.md
  babel.config.js
  console/build_esm_lib
  console/build_esm_lib.ts
  deps.ts
  egg.json
  example_tests/basic/1.ts
  example_tests/basic/1_fail.ts
  example_tests/basic/2.ts
  example_tests/basic/3.ts
  example_tests/basic/tests_fail.ts
  example_tests/basic/tests_pass.ts
  jest.config.ts
  mod.ts
  package.json
  src/fake/fake_builder.ts
  src/fake/fake_mixin.ts
  src/interfaces.ts
  src/mock/mock_builder.ts
  src/mock/mock_mixin.ts
  src/mock_builder.ts
  src/pre_programmed_method.ts
  src/rhum_asserts.ts
  src/test_case.ts
  src/types.ts
  tests/cjs/unit/mod/dummy.test.js
  tests/cjs/unit/mod/fake.test.js
  tests/cjs/unit/mod/mock.test.js
  tests/cjs/unit/mod/stub.test.js
  tests/deno/deps.ts
  tests/deno/unit/mod/dummy_test.ts
  tests/deno/unit/mod/fake_test.ts
  tests/deno/unit/mod/mock_test.ts
  tests/deno/unit/mod/stub_test.ts
  tests/deps.ts
  tests/esm/jest_assertions.ts
  tests/esm/unit/mod/dummy.test.ts
  tests/esm/unit/mod/fake.test.ts
  tests/esm/unit/mod/mock.test.ts
  tests/esm/unit/mod/stub.test.ts
  tests/integration/asserts_test.ts
  tests/integration/hooks/after_all_test.ts
  tests/integration/hooks/after_each_test.ts
  tests/integration/hooks/before_all_test.ts
  tests/integration/hooks/before_each_test.ts
  tests/integration/mock_test.ts
  tests/integration/stub_test.ts
  tests/unit/mock_builder_test.ts
  tests/unit/mod_test.ts
  tests/unit/quick_start.ts
  tests/unit/test_case_test.ts
  tsconfig.cjs.json
  tsconfig.esm.json
  tsconfig.json
Labels: Type: Major
